---

- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
      - docker.io 
      - containerd
      - runc
    state: absent

- name: Install required system packages
  package:
      name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - gnupg2
      state: latest
      update_cache: true
  become: true

- name: Add docker gpg key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmor  -o /etc/apt/trusted.gpg.d/docker.gpg"
  args:
    creates: /etc/apt/trusted.gpg.d/docker.gpg

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ architecture }} signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: true

- name: Update cache and install docker
  package:
    name: 
      - docker-ce
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
    state: latest
    update_cache: true
  become: true

- name: Install Docker Module for Python
  pip:
    name: 
      - docker
      - docker-compose
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: "docker"
    append: true
  become: true